# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/juliarmn/Projetinho_SO

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/juliarmn/Projetinho_SO

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/juliarmn/Projetinho_SO/CMakeFiles /home/juliarmn/Projetinho_SO//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/juliarmn/Projetinho_SO/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GatuOS

# Build rule for target.
GatuOS: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GatuOS
.PHONY : GatuOS

# fast build rule for target.
GatuOS/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GatuOS.dir/build.make CMakeFiles/GatuOS.dir/build
.PHONY : GatuOS/fast

ES/imprimir.o: ES/imprimir.c.o
.PHONY : ES/imprimir.o

# target to build an object file
ES/imprimir.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GatuOS.dir/build.make CMakeFiles/GatuOS.dir/ES/imprimir.c.o
.PHONY : ES/imprimir.c.o

ES/imprimir.i: ES/imprimir.c.i
.PHONY : ES/imprimir.i

# target to preprocess a source file
ES/imprimir.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GatuOS.dir/build.make CMakeFiles/GatuOS.dir/ES/imprimir.c.i
.PHONY : ES/imprimir.c.i

ES/imprimir.s: ES/imprimir.c.s
.PHONY : ES/imprimir.s

# target to generate assembly for a file
ES/imprimir.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GatuOS.dir/build.make CMakeFiles/GatuOS.dir/ES/imprimir.c.s
.PHONY : ES/imprimir.c.s

disco/disco.o: disco/disco.c.o
.PHONY : disco/disco.o

# target to build an object file
disco/disco.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GatuOS.dir/build.make CMakeFiles/GatuOS.dir/disco/disco.c.o
.PHONY : disco/disco.c.o

disco/disco.i: disco/disco.c.i
.PHONY : disco/disco.i

# target to preprocess a source file
disco/disco.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GatuOS.dir/build.make CMakeFiles/GatuOS.dir/disco/disco.c.i
.PHONY : disco/disco.c.i

disco/disco.s: disco/disco.c.s
.PHONY : disco/disco.s

# target to generate assembly for a file
disco/disco.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GatuOS.dir/build.make CMakeFiles/GatuOS.dir/disco/disco.c.s
.PHONY : disco/disco.c.s

escalonador/rr.o: escalonador/rr.c.o
.PHONY : escalonador/rr.o

# target to build an object file
escalonador/rr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GatuOS.dir/build.make CMakeFiles/GatuOS.dir/escalonador/rr.c.o
.PHONY : escalonador/rr.c.o

escalonador/rr.i: escalonador/rr.c.i
.PHONY : escalonador/rr.i

# target to preprocess a source file
escalonador/rr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GatuOS.dir/build.make CMakeFiles/GatuOS.dir/escalonador/rr.c.i
.PHONY : escalonador/rr.c.i

escalonador/rr.s: escalonador/rr.c.s
.PHONY : escalonador/rr.s

# target to generate assembly for a file
escalonador/rr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GatuOS.dir/build.make CMakeFiles/GatuOS.dir/escalonador/rr.c.s
.PHONY : escalonador/rr.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GatuOS.dir/build.make CMakeFiles/GatuOS.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GatuOS.dir/build.make CMakeFiles/GatuOS.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GatuOS.dir/build.make CMakeFiles/GatuOS.dir/main.c.s
.PHONY : main.c.s

memoria/memoria.o: memoria/memoria.c.o
.PHONY : memoria/memoria.o

# target to build an object file
memoria/memoria.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GatuOS.dir/build.make CMakeFiles/GatuOS.dir/memoria/memoria.c.o
.PHONY : memoria/memoria.c.o

memoria/memoria.i: memoria/memoria.c.i
.PHONY : memoria/memoria.i

# target to preprocess a source file
memoria/memoria.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GatuOS.dir/build.make CMakeFiles/GatuOS.dir/memoria/memoria.c.i
.PHONY : memoria/memoria.c.i

memoria/memoria.s: memoria/memoria.c.s
.PHONY : memoria/memoria.s

# target to generate assembly for a file
memoria/memoria.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GatuOS.dir/build.make CMakeFiles/GatuOS.dir/memoria/memoria.c.s
.PHONY : memoria/memoria.c.s

processo/process.o: processo/process.c.o
.PHONY : processo/process.o

# target to build an object file
processo/process.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GatuOS.dir/build.make CMakeFiles/GatuOS.dir/processo/process.c.o
.PHONY : processo/process.c.o

processo/process.i: processo/process.c.i
.PHONY : processo/process.i

# target to preprocess a source file
processo/process.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GatuOS.dir/build.make CMakeFiles/GatuOS.dir/processo/process.c.i
.PHONY : processo/process.c.i

processo/process.s: processo/process.c.s
.PHONY : processo/process.s

# target to generate assembly for a file
processo/process.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GatuOS.dir/build.make CMakeFiles/GatuOS.dir/processo/process.c.s
.PHONY : processo/process.c.s

semaforo/semaforo.o: semaforo/semaforo.c.o
.PHONY : semaforo/semaforo.o

# target to build an object file
semaforo/semaforo.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GatuOS.dir/build.make CMakeFiles/GatuOS.dir/semaforo/semaforo.c.o
.PHONY : semaforo/semaforo.c.o

semaforo/semaforo.i: semaforo/semaforo.c.i
.PHONY : semaforo/semaforo.i

# target to preprocess a source file
semaforo/semaforo.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GatuOS.dir/build.make CMakeFiles/GatuOS.dir/semaforo/semaforo.c.i
.PHONY : semaforo/semaforo.c.i

semaforo/semaforo.s: semaforo/semaforo.c.s
.PHONY : semaforo/semaforo.s

# target to generate assembly for a file
semaforo/semaforo.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GatuOS.dir/build.make CMakeFiles/GatuOS.dir/semaforo/semaforo.c.s
.PHONY : semaforo/semaforo.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... GatuOS"
	@echo "... ES/imprimir.o"
	@echo "... ES/imprimir.i"
	@echo "... ES/imprimir.s"
	@echo "... disco/disco.o"
	@echo "... disco/disco.i"
	@echo "... disco/disco.s"
	@echo "... escalonador/rr.o"
	@echo "... escalonador/rr.i"
	@echo "... escalonador/rr.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... memoria/memoria.o"
	@echo "... memoria/memoria.i"
	@echo "... memoria/memoria.s"
	@echo "... processo/process.o"
	@echo "... processo/process.i"
	@echo "... processo/process.s"
	@echo "... semaforo/semaforo.o"
	@echo "... semaforo/semaforo.i"
	@echo "... semaforo/semaforo.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

